openapi: 3.0.0
info:
    title: PizzaShackAPI
    version: 1.0.0
servers:
    -   url: https://localhost:8243/pizzashack/1.0.0/
paths:
    /menu:
        get:
            description: Return a list of available menu items
            responses:
                '200':
                    description: OK. List of pizzas is returned.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/MenuItem'
components:
    schemas:
        MenuItem:
            title: Pizza menu Item
            required:
                - name
            properties:
                price:
                    type: string
                description:
                    type: string
                name:
                    type: string
                image:
                    type: string